scene: rgbd_dataset_freiburg3_walking_static
inherit_from: configs/TUM_RGBD/tum.yaml
config_path: configs/TUM_RGBD/freiburg3_walking_static.yaml
data:
  input_folder: /home/ubuntu/Downloads/rgbd_dataset_freiburg3_walking_static_point_slam
  output: output/TUM_RGBD/rgbd_dataset_freiburg3_walking_static
cam:  #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 480 
  W: 640 
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6
  crop_edge: 8
